#!/usr/bin/python3

import datetime
import time

import goeapi
import smaxsmt

SOLAR = "192.168.178.155"
GO_E = "192.168.178.109"


if __name__ == "__main__":
    smax = smaxsmt.SolarmaxSmt(SOLAR)
    goe = goeapi.GoeAPI(GO_E)

    current_phases = goe.phases
    current_ampere = goe.ampere
    while True:
        # XXX: detect car and do nothing if no car(?)
        # XXX3: telegram integration?
        # XXX4: support for 1-3 phases

        # detect if the the user manually overrode the automatic
        # settings, e.g. to load faster - just do nothing then unti
        # the car is disconnected
        car_connected = goe.car_connected
        if (
            not goe.force_pause
            and car_connected
            and (current_ampere != goe.ampere or current_phases != goe.phases)
        ):
            print(
                "ampere or phases got manually overriden "
                "got {}/{}, expected {}/{}) sleeping until car "
                "disconnects".format(
                    goe.ampere, goe.phases, current_ampere, current_phases
                ),
                flush=True,
            )
            time.sleep(5 * 60)
            continue

        # sleep *long* in the night and ensure that we not accidentally load
        now = datetime.datetime.now()
        if now.hour >= 20 or now.hour < 6:
            print("night mode, sleeping for 30min ({})".format(now), flush=True)
            if not goe.force_pause:
                print("evening mode: force pause (wasn't already?)", flush=True)
                goe.force_pause = True
            time.sleep(30 * 60)

        current_power_charger = goe.power
        try:
            current_solar_power = smax.current_power
        except (smaxsmt.ModbusConnectionError, AttributeError):
            # XXX: deal with the attribute error in the high layers
            #
            # Traceback (most recent call last):
            #  File "/snap/eloader-mvo/56/bin/eloader", line 35, in <module>
            #    current_solar_power = smax.current_power
            #  File "/.../smaxsmt.py", line 62, in current_power
            #    return self._get(reg)
            #  File "/.../smaxsmt.py", line 55, in _get
            #    val = reg.output(mc)
            #  File "/.../smaxsmt.py", line 20, in output
            #    if len(reg.registers) == 1:
            # AttributeError: 'ModbusIOException' object has no attribute 'registers'
            RETRY_WAIT = 60
            print("cannot connect, will retry in {}s".format(RETRY_WAIT), flush=True)
            time.sleep(RETRY_WAIT)
            continue
        print(
            "{} solar / charger {} kW".format(
                current_solar_power, current_power_charger / 1000.0
            )
        )
        # XXX: deal with 1->3 phase and vice versa
        next_amp = None
        for amp in [6, 10, 12, 14, 16]:
            pw = 220 * amp * current_phases / 1000.0
            if pw > current_solar_power:
                break
            next_amp = amp
        if current_ampere != next_amp:
            if next_amp is None:
                print("not enough power, forcing pause")
                goe.force_pause = True
            if next_amp is not None:
                if goe.force_pause:
                    print("enough power, un-pause")
                    goe.force_pause = False
                goe.ampere = next_amp
                new_kw = 220 * next_amp * current_phases / 1000.0
                print("switched to {} amp ({} kW)".format(next_amp, new_kw))
            current_ampere = next_amp
        else:
            print("staying at {} amp".format(current_ampere))
        print(flush=True)
        # wait a bit
        # empirically anything less than 360s here will mean no more
        # data is sent to maxmonitoring.solarmax.com for unknown reasons
        time.sleep(360)
